-- begin VPS_DIVISION
alter table VPS_DIVISION add constraint FK_VPS_DIVISION_COUNTY foreign key (COUNTY_ID) references VPS_COUNTIES(ID)^
create index IDX_VPS_DIVISION_COUNTY on VPS_DIVISION (COUNTY_ID)^
-- end VPS_DIVISION
-- begin VPS_SUB_COUNTIES
alter table VPS_SUB_COUNTIES add constraint FK_VPS_SUB_COUNTIES_COUNTY foreign key (COUNTY_ID) references VPS_COUNTIES(ID)^
create index IDX_VPS_SUB_COUNTIES_COUNTY on VPS_SUB_COUNTIES (COUNTY_ID)^
-- end VPS_SUB_COUNTIES
-- begin VPS_STATIONS
alter table VPS_STATIONS add constraint FK_VPS_STATIONS_DIVISION foreign key (DIVISION_ID) references VPS_DIVISION(ID)^
create index IDX_VPS_STATIONS_DIVISION on VPS_STATIONS (DIVISION_ID)^
-- end VPS_STATIONS
-- begin VPS_OCCURRENCES_OCCURRENCE_TYPES_LINK
alter table VPS_OCCURRENCES_OCCURRENCE_TYPES_LINK add constraint FK_OCCOCCTYP_OCCURRENCES foreign key (OCCURRENCES_ID) references VPS_OCCURRENCES(ID)^
alter table VPS_OCCURRENCES_OCCURRENCE_TYPES_LINK add constraint FK_OCCOCCTYP_OCCURRENCE_TYPES foreign key (OCCURRENCE_TYPES_ID) references VPS_OCCURRENCE_TYPES(ID)^
-- end VPS_OCCURRENCES_OCCURRENCE_TYPES_LINK
-- begin VPS_OCCURRENCES_OCCURRENCE_STATUS_LINK
alter table VPS_OCCURRENCES_OCCURRENCE_STATUS_LINK add constraint FK_OCCOCCSTA_OCCURRENCES foreign key (OCCURRENCES_ID) references VPS_OCCURRENCES(ID)^
alter table VPS_OCCURRENCES_OCCURRENCE_STATUS_LINK add constraint FK_OCCOCCSTA_OCCURRENCE_STATUS foreign key (OCCURRENCE_STATUS_ID) references VPS_OCCURRENCE_STATUS(ID)^
-- end VPS_OCCURRENCES_OCCURRENCE_STATUS_LINK
-- begin SEC_USER
alter table SEC_USER add constraint FK_SEC_USER_STATION foreign key (STATION_ID) references VPS_STATIONS(ID)^
create index IDX_SEC_USER_STATION on SEC_USER (STATION_ID)^
-- end SEC_USER
