alter table VPS_OCCURRENCES_OCCURRENCE_TYPES_LINK add constraint FK_OCCOCCTYP_OCCURRENCES foreign key (OCCURRENCES_ID) references VPS_OCCURRENCES(ID);
alter table VPS_OCCURRENCES_OCCURRENCE_TYPES_LINK add constraint FK_OCCOCCTYP_OCCURRENCE_TYPES foreign key (OCCURRENCE_TYPES_ID) references VPS_OCCURRENCE_TYPES(ID);
